In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score, accuracy_score

from sklearn.model_selection import train_test_split

import warnings
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

import matplotlib.pyplot as plt

In [2]:
trainmydata = pd.read_csv("C:/E_Drive/train_fktp.txt")

In [3]:
testmydata = pd.read_csv("C:/E_Drive/test_fktp.txt")

C:\Users\ACER\AppData\Local\Temp\ipykernel_1784\4188100633.py:1: DtypeWarning: Columns (3,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  testmydata = pd.read_csv("C:/E_Drive/test_fktp.txt")

In [4]:
trainmydata

,157978748,50765420,20.0649833679199,958073632,2019-08-01,2019-08-01.1,61,6108,3,1,...,9999.1,9999.2,98,9998,98.1,98.2,98.3,98.4,2.1,Sehat
0,95085112.0,26931775,2.626307,449590620P000054,2020-06-17,2020-06-17,51,5171,9,3,...,K297,"Gastritis, unspecified",98,9998,98,98,98,98,1,Belum_Sehat
1,224470578.0,227368233,1.051830,467490619P000001,2019-06-01,2019-06-01,35,3516,9,2,...,Z309,"Contraceptive management, unspecified",98,9998,98,98,98,98,1,Belum_Sehat
2,63871289.0,62313678,364.741455,254321219Y002368,2019-12-21,2019-12-21,34,3402,3,1,...,I10,Essential (primary) hypertension,98,9998,98,98,98,98,1,Belum_Sehat
3,29915626.0,113446188,1.050523,88681119P000020,2019-11-04,2019-11-04,35,3509,3,1,...,I110,Hypertensive heart disease with (congestive) h...,98,9998,98,98,98,98,1,Belum_Sehat
4,189355720.0,69855169,30.044949,97010720P000238,2020-07-15,2020-07-15,62,6206,3,1,...,I10,Essential (primary) hypertension,98,9998,98,98,98,98,1,Belum_Sehat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4056892,212666736.0,91270403,14.246229,1285820875,2020-07-29,2020-07-29,35,3505,9,3,...,9999,9999,98,9998,98,98,98,98,2,Sehat
4056893,30859241.0,30859241,3.886934,315641120P000514,2020-11-14,2020-11-14,35,3514,9,2,...,H269,"Cataract, unspecified",35,3514,9,2,14,99,1,Belum_Sehat
4056894,8859416.0,8859416,6.146070,962412926,2019-08-16,2019-08-16,11,1171,4,2,...,9999,9999,98,9998,98,98,98,98,2,Sehat
4056895,399491834.0,399491834,26.548826,273170420P000003,2020-04-01,2020-04-01,74,7402,3,1,...,K30,Dyspepsia,98,9998,98,98,98,98,1,Belum_Sehat
4056896,99146724.0,39321920,88.348953,1188955927,2020-03-14,2020-03-14,73,7317,3,1,...,9999,9999,98,9998,98,98,98,98,2,Sehat

In [5]:
testmydata

,187883292,98048784,240.884841918945,954386050,2019-08-21,2019-08-21.1,31,3172,9,2,...,Unnamed: 15,9999.1,9999.2,98,9998,98.1,98.2,98.3,98.4,2.1
0,123307139.0,20969999,47.378571,774246805,2019-02-12,2019-02-12,17,1705,3,1,...,NaN,9999,9999,98,9998,98,98,98,98,2
1,21416273.0,21416273,5.882927,1202010273,2020-03-27,2020-03-27,64,6402,3,1,...,NaN,9999,9999,98,9998,98,98,98,98,2
2,97630052.0,97630052,172.916031,1286640248,2020-07-30,2020-07-30,18,1872,9,2,...,NaN,9999,9999,98,9998,98,98,98,98,2
3,124531163.0,124531163,187.203140,1285179242,2020-07-28,2020-07-28,18,1809,9,2,...,NaN,9999,9999,98,9998,98,98,98,98,2
4,68434306.0,77074451,17.472210,1050998453,2019-11-19,2019-11-19,33,3374,9,3,...,NaN,9999,9999,98,9998,98,98,98,98,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014219,51801010.0,51801010,7.563763,248870919P000406,2019-09-08,2019-09-08,36,3601,9,2,...,Z99,Z992,Dependence on renal dialysis,36,3602,3,1,27,99,1
1014220,339397889.0,339397889,11.063568,116000620P000034,2020-06-02,2020-06-02,33,3373,9,2,...,Z99,Z999,Dependence on unspecified enabling machine and...,98,9998,98,98,98,98,1
1014221,76213152.0,76213152,286.792694,160421019P000631,2019-10-15,2019-10-15,32,3276,3,1,...,Z99,Z992,Dependence on renal dialysis,32,3276,9,1,33,99,1
1014222,101797983.0,101797983,30.222155,332670919P000083,2019-09-06,2019-09-06,16,1606,3,1,...,Z99,Z992,Dependence on renal dialysis,16,1606,3,1,27,99,1
1014223,20239553.0,20239553,233.636230,106050119Y000587,2019-01-30,2019-01-30,19,1904,3,1,...,Z99,Z992,Dependence on renal dialysis,19,1971,3,1,28,99,1

In [6]:
colnames = ['Nomor peserta', 'Nomor keluarga', 'Bobot', 'ID Kunjungan FKTP', 'Tanggal datang kunjungan FKTP', 
            'Tanggal pulang kunjungan FKTP', 'Provinsi FKTP', 'Kabupaten/Kota FKTP', 'Kepemilikan FKTP',
            'Jenis FKTP', 'Tipe FKTP', 'Tingkat Pelayanan FKTP', 'Jenis Poli FKTP', 'Segmen Peserta saat akses layanan FKTP',
            'Kode dan nama diagnosis ICD 10 (3 digit)', 'Kode diagnosis ICD 10 (3 digit)', 'Kode diagnosis (beragam 3-5 digit)',
            'Nama diagnosis berasal dari kode diagnosis FKP15', 'Provinsi faskes tujuan rujukan',
            'Kabupaten/Kota faskes tujuan rujukan', 'Kepemilikan faskes tujuan rujukan', 'Jenis faskes tujuan rujukan',
            'Tipe faskes tujuan rujukan', 'Poli faskes tujuan rujukan', 'Jenis Kunjungan FKTP', 'Kelas Status Pulang Peserta']

mydata_train=pd.read_csv("C:/E_Drive/train_fktp.txt", names=colnames)
mydata_train

,Nomor peserta,Nomor keluarga,Bobot,ID Kunjungan FKTP,Tanggal datang kunjungan FKTP,Tanggal pulang kunjungan FKTP,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,...,Kode diagnosis (beragam 3-5 digit),Nama diagnosis berasal dari kode diagnosis FKP15,Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP,Kelas Status Pulang Peserta
0,157978748.0,50765420,20.064983,958073632,2019-08-01,2019-08-01,61,6108,3,1,...,9999,9999,98,9998,98,98,98,98,2,Sehat
1,95085112.0,26931775,2.626307,449590620P000054,2020-06-17,2020-06-17,51,5171,9,3,...,K297,"Gastritis, unspecified",98,9998,98,98,98,98,1,Belum_Sehat
2,224470578.0,227368233,1.051830,467490619P000001,2019-06-01,2019-06-01,35,3516,9,2,...,Z309,"Contraceptive management, unspecified",98,9998,98,98,98,98,1,Belum_Sehat
3,63871289.0,62313678,364.741455,254321219Y002368,2019-12-21,2019-12-21,34,3402,3,1,...,I10,Essential (primary) hypertension,98,9998,98,98,98,98,1,Belum_Sehat
4,29915626.0,113446188,1.050523,88681119P000020,2019-11-04,2019-11-04,35,3509,3,1,...,I110,Hypertensive heart disease with (congestive) h...,98,9998,98,98,98,98,1,Belum_Sehat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4056893,212666736.0,91270403,14.246229,1285820875,2020-07-29,2020-07-29,35,3505,9,3,...,9999,9999,98,9998,98,98,98,98,2,Sehat
4056894,30859241.0,30859241,3.886934,315641120P000514,2020-11-14,2020-11-14,35,3514,9,2,...,H269,"Cataract, unspecified",35,3514,9,2,14,99,1,Belum_Sehat
4056895,8859416.0,8859416,6.146070,962412926,2019-08-16,2019-08-16,11,1171,4,2,...,9999,9999,98,9998,98,98,98,98,2,Sehat
4056896,399491834.0,399491834,26.548826,273170420P000003,2020-04-01,2020-04-01,74,7402,3,1,...,K30,Dyspepsia,98,9998,98,98,98,98,1,Belum_Sehat
4056897,99146724.0,39321920,88.348953,1188955927,2020-03-14,2020-03-14,73,7317,3,1,...,9999,9999,98,9998,98,98,98,98,2,Sehat

In [7]:
colnames = ['Nomor peserta', 'Nomor keluarga', 'Bobot', 'ID Kunjungan FKTP', 'Tanggal datang kunjungan FKTP', 
            'Tanggal pulang kunjungan FKTP', 'Provinsi FKTP', 'Kabupaten/Kota FKTP', 'Kepemilikan FKTP',
            'Jenis FKTP', 'Tipe FKTP', 'Tingkat Pelayanan FKTP', 'Jenis Poli FKTP', 'Segmen Peserta saat akses layanan FKTP',
            'Kode dan nama diagnosis ICD 10 (3 digit)', 'Kode diagnosis ICD 10 (3 digit)', 'Kode diagnosis (beragam 3-5 digit)',
            'Nama diagnosis berasal dari kode diagnosis FKP15', 'Provinsi faskes tujuan rujukan',
            'Kabupaten/Kota faskes tujuan rujukan', 'Kepemilikan faskes tujuan rujukan', 'Jenis faskes tujuan rujukan',
            'Tipe faskes tujuan rujukan', 'Poli faskes tujuan rujukan', 'Jenis Kunjungan FKTP']

mydata_test=pd.read_csv("C:/E_Drive/test_fktp.txt", names=colnames)
mydata_test

C:\Users\ACER\AppData\Local\Temp\ipykernel_1784\3894715058.py:9: DtypeWarning: Columns (3,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  mydata_test=pd.read_csv("C:/E_Drive/test_fktp.txt", names=colnames)

,Nomor peserta,Nomor keluarga,Bobot,ID Kunjungan FKTP,Tanggal datang kunjungan FKTP,Tanggal pulang kunjungan FKTP,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,...,Kode diagnosis ICD 10 (3 digit),Kode diagnosis (beragam 3-5 digit),Nama diagnosis berasal dari kode diagnosis FKP15,Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP
0,187883292.0,98048784,240.884842,954386050,2019-08-21,2019-08-21,31,3172,9,2,...,NaN,9999,9999,98,9998,98,98,98,98,2
1,123307139.0,20969999,47.378571,774246805,2019-02-12,2019-02-12,17,1705,3,1,...,NaN,9999,9999,98,9998,98,98,98,98,2
2,21416273.0,21416273,5.882927,1202010273,2020-03-27,2020-03-27,64,6402,3,1,...,NaN,9999,9999,98,9998,98,98,98,98,2
3,97630052.0,97630052,172.916031,1286640248,2020-07-30,2020-07-30,18,1872,9,2,...,NaN,9999,9999,98,9998,98,98,98,98,2
4,124531163.0,124531163,187.203140,1285179242,2020-07-28,2020-07-28,18,1809,9,2,...,NaN,9999,9999,98,9998,98,98,98,98,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014220,51801010.0,51801010,7.563763,248870919P000406,2019-09-08,2019-09-08,36,3601,9,2,...,Z99,Z992,Dependence on renal dialysis,36,3602,3,1,27,99,1
1014221,339397889.0,339397889,11.063568,116000620P000034,2020-06-02,2020-06-02,33,3373,9,2,...,Z99,Z999,Dependence on unspecified enabling machine and...,98,9998,98,98,98,98,1
1014222,76213152.0,76213152,286.792694,160421019P000631,2019-10-15,2019-10-15,32,3276,3,1,...,Z99,Z992,Dependence on renal dialysis,32,3276,9,1,33,99,1
1014223,101797983.0,101797983,30.222155,332670919P000083,2019-09-06,2019-09-06,16,1606,3,1,...,Z99,Z992,Dependence on renal dialysis,16,1606,3,1,27,99,1
1014224,20239553.0,20239553,233.636230,106050119Y000587,2019-01-30,2019-01-30,19,1904,3,1,...,Z99,Z992,Dependence on renal dialysis,19,1971,3,1,28,99,1

In [8]:
#menghitung missing value
mydata_train.isnull().sum()

Nomor peserta                                             0
Nomor keluarga                                            0
Bobot                                                     0
ID Kunjungan FKTP                                         0
Tanggal datang kunjungan FKTP                             0
Tanggal pulang kunjungan FKTP                             0
Provinsi FKTP                                             0
Kabupaten/Kota FKTP                                       0
Kepemilikan FKTP                                          0
Jenis FKTP                                                0
Tipe FKTP                                                 0
Tingkat Pelayanan FKTP                                    0
Jenis Poli FKTP                                           1
Segmen Peserta saat akses layanan FKTP                    0
Kode dan nama diagnosis ICD 10 (3 digit)                  0
Kode diagnosis ICD 10 (3 digit)                     1380241
Kode diagnosis (beragam 3-5 digit)                        0
Nama diagnosis berasal dari kode diagnosis FKP15          0
Provinsi faskes tujuan rujukan                            0
Kabupaten/Kota faskes tujuan rujukan                      0
Kepemilikan faskes tujuan rujukan                         0
Jenis faskes tujuan rujukan                               0
Tipe faskes tujuan rujukan                                0
Poli faskes tujuan rujukan                                0
Jenis Kunjungan FKTP                                      0
Kelas Status Pulang Peserta                               0
dtype: int64

In [9]:
mydata_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4056898 entries, 0 to 4056897
Data columns (total 26 columns):
 #   Column                                            Dtype
---  ------                                            -----
 0   Nomor peserta                                     float64
 1   Nomor keluarga                                    int64
 2   Bobot                                             float64
 3   ID Kunjungan FKTP                                 object
 4   Tanggal datang kunjungan FKTP                     object
 5   Tanggal pulang kunjungan FKTP                     object
 6   Provinsi FKTP                                     int64
 7   Kabupaten/Kota FKTP                               int64
 8   Kepemilikan FKTP                                  int64
 9   Jenis FKTP                                        int64
 10  Tipe FKTP                                         int64
 11  Tingkat Pelayanan FKTP                            int64
 12  Jenis Poli FKTP                                   float64
 13  Segmen Peserta saat akses layanan FKTP            int64
 14  Kode dan nama diagnosis ICD 10 (3 digit)          int64
 15  Kode diagnosis ICD 10 (3 digit)                   object
 16  Kode diagnosis (beragam 3-5 digit)                object
 17  Nama diagnosis berasal dari kode diagnosis FKP15  object
 18  Provinsi faskes tujuan rujukan                    int64
 19  Kabupaten/Kota faskes tujuan rujukan              int64
 20  Kepemilikan faskes tujuan rujukan                 int64
 21  Jenis faskes tujuan rujukan                       int64
 22  Tipe faskes tujuan rujukan                        int64
 23  Poli faskes tujuan rujukan                        int64
 24  Jenis Kunjungan FKTP                              int64
 25  Kelas Status Pulang Peserta                       object
dtypes: float64(3), int64(16), object(7)
memory usage: 804.7+ MB

In [10]:
mydata_train.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
4056893    False
4056894    False
4056895    False
4056896    False
4056897    False
Length: 4056898, dtype: bool

In [11]:
#mengisi variabel missing punya  "jenis poli fktp"
mean_value=mydata_train["Jenis Poli FKTP"].mean()
mydata_train["Jenis Poli FKTP"] = mydata_train["Jenis Poli FKTP"].fillna(mean_value)

In [12]:
mydata_train.isnull().sum()

Nomor peserta                                             0
Nomor keluarga                                            0
Bobot                                                     0
ID Kunjungan FKTP                                         0
Tanggal datang kunjungan FKTP                             0
Tanggal pulang kunjungan FKTP                             0
Provinsi FKTP                                             0
Kabupaten/Kota FKTP                                       0
Kepemilikan FKTP                                          0
Jenis FKTP                                                0
Tipe FKTP                                                 0
Tingkat Pelayanan FKTP                                    0
Jenis Poli FKTP                                           0
Segmen Peserta saat akses layanan FKTP                    0
Kode dan nama diagnosis ICD 10 (3 digit)                  0
Kode diagnosis ICD 10 (3 digit)                     1380241
Kode diagnosis (beragam 3-5 digit)                        0
Nama diagnosis berasal dari kode diagnosis FKP15          0
Provinsi faskes tujuan rujukan                            0
Kabupaten/Kota faskes tujuan rujukan                      0
Kepemilikan faskes tujuan rujukan                         0
Jenis faskes tujuan rujukan                               0
Tipe faskes tujuan rujukan                                0
Poli faskes tujuan rujukan                                0
Jenis Kunjungan FKTP                                      0
Kelas Status Pulang Peserta                               0
dtype: int64

In [13]:
mydata_train['Kode diagnosis ICD 10 (3 digit)'].tolist()

[nan,
 'K29',
 'Z30',
 'I10',
 'I11',
 'I10',
 nan,
 nan,
 nan,
 'M15',
 nan,
 'L29',
 nan,
 'I10',
 nan,
 'I10',
 'J06',
 'K08',
 'G44',
 'H10',
 'K04',
 'K04',
 nan,
 'J03',
 'J06',
 'S91',
 nan,
 nan,
 'K29',
 'M79',
 'J06',
 nan,
 nan,
 'Z00',
 nan,
 nan,
 'H52',
 'K30',
 'J06',
 'J06',
 'A09',
 'Z71',
 nan,
 nan,
 'Z36',
 nan,
 'R50',
 nan,
 'L23',
 nan,
 nan,
 nan,
 'K30',
 'J06',
 'J06',
 'K04',
 'R05',
 'J06',
 'J06',
 'K30',
 'L23',
 'L30',
 nan,
 'M81',
 nan,
 'J03',
 'K30',
 'M79',
 'I10',
 'K21',
 nan,
 'I11',
 'G80',
 'N30',
 'L50',
 'K30',
 'K29',
 nan,
 'I10',
 nan,
 nan,
 nan,
 'J00',
 nan,
 'E11',
 nan,
 nan,
 'A09',
 'E10',
 'M79',
 'H61',
 nan,
 nan,
 'A06',
 nan,
 'H52',
 'E14',
 'K04',
 nan,
 nan,
 nan,
 nan,
 'R52',
 'K30',
 'J06',
 nan,
 'Z09',
 'J96',
 'Z34',
 'H04',
 'T14',
 nan,
 'R51',
 'R50',
 'J00',
 'I10',
 'I10',
 'L02',
 'E13',
 nan,
 'K30',
 nan,
 'J00',
 'E11',
 nan,
 'K30',
 'J40',
 'J11',
 nan,
 'I63',
 'K27',
 'F29',
 'R51',
 'M06',
 nan,
 'Z00',
 'R51',
 'M54',
 'E78',
 'J06',
 'G58',
 nan,
 nan,
 'A02',
 'R59',
 'I64',
 nan,
 'K30',
 'K00',
 nan,
 nan,
 'K29',
 'Z39',
 'J00',
 'Z30',
 nan,
 'R05',
 'H26',
 'N13',
 'R51',
 'T30',
 nan,
 'J00',
 'A01',
 'I10',
 'J22',
 'G43',
 'R51',
 'K02',
 'L20',
 'G40',
 nan,
 'J02',
 'R50',
 nan,
 'I21',
 nan,
 'O21',
 'R05',
 nan,
 nan,
 nan,
 nan,
 'R51',
 nan,
 nan,
 nan,
 'R51',
 nan,
 'K30',
 nan,
 'L30',
 'J06',
 'A09',
 'T78',
 'R50',
 nan,
 'K30',
 'H52',
 'C49',
 'K29',
 'I69',
 nan,
 'I21',
 nan,
 'M79',
 nan,
 nan,
 'N18',
 'J06',
 'I11',
 'M25',
 'J03',
 nan,
 nan,
 nan,
 nan,
 'M13',
 nan,
 'J06',
 nan,
 'H52',
 'F20',
 'K29',
 'J02',
 nan,
 nan,
 'A09',
 'J06',
 'J00',
 'J11',
 'H11',
 'J06',
 nan,
 'K29',
 'D21',
 'I50',
 'I64',
 'K29',
 'I20',
 nan,
 'M13',
 'K29',
 'H47',
 'R50',
 nan,
 nan,
 'Z30',
 nan,
 nan,
 nan,
 'E11',
 nan,
 nan,
 'H52',
 'K30',
 nan,
 'J00',
 'R51',
 'J06',
 'K29',
 'L97',
 nan,
 nan,
 'N39',
 nan,
 nan,
 nan,
 'A79',
 'K80',
 nan,
 'K04',
 'K05',
 'R42',
 nan,
 'J45',
 'R10',
 nan,
 nan,
 'K30',
 'O48',
 'J02',
 'J06',
 'J45',
 nan,
 'L30',
 nan,
 nan,
 'J45',
 'E11',
 nan,
 nan,
 nan,
 nan,
 'Z36',
 'J00',
 nan,
 'L28',
 'F20',
 'K30',
 nan,
 'A15',
 'J44',
 nan,
 'H54',
 'J06',
 'L98',
 'G43',
 nan,
 'M06',
 nan,
 'N83',
 'H52',
 'M79',
 'G44',
 'A09',
 nan,
 'K04',
 'E11',
 'Z01',
 'M17',
 'K29',
 'M79',
 nan,
 'Z03',
 'D48',
 nan,
 'A30',
 'D17',
 'Z32',
 nan,
 'K30',
 nan,
 nan,
 nan,
 nan,
 'J00',
 nan,
 'A09',
 'I10',
 'R50',
 'G44',
 'K29',
 nan,
 'I11',
 'E11',
 'J44',
 nan,
 'J44',
 nan,
 nan,
 'O42',
 'E11',
 nan,
 'K29',
 'M06',
 'Z32',
 nan,
 'J00',
 'I10',
 'R51',
 nan,
 nan,
 'L23',
 nan,
 'K29',
 nan,
 'I10',
 nan,
 nan,
 nan,
 'J06',
 'H04',
 nan,
 'K04',
 'R51',
 'J00',
 nan,
 'M79',
 'B01',
 'I10',
 'R47',
 nan,
 'J06',
 nan,
 nan,
 nan,
 nan,
 'I10',
 nan,
 nan,
 'I69',
 'L30',
 'J02',
 'J00',
 'I10',
 'O80',
 'J00',
 'J02',
 'Z00',
 'R50',
 'R29',
 'A41',
 'M79',
 nan,
 'K04',
 'J06',
 nan,
 nan,
 'J06',
 nan,
 nan,
 nan,
 'M79',
 nan,
 'L23',
 'I15',
 nan,
 'J30',
 'J06',
 'K29',
 'K29',
 'I84',
 'J00',
 'M79',
 'R51',
 nan,
 'K29',
 'H10',
 nan,
 nan,
 nan,
 nan,
 nan,
 'I10',
 'M79',
 'E11',
 'J11',
 'I06',
 'J00',
 'M79',
 nan,
 nan,
 nan,
 nan,
 'I15',
 'L23',
 'B35',
 'J06',
 nan,
 'B06',
 nan,
 'K29',
 nan,
 nan,
 'I15',
 'M19',
 'I84',
 'I11',
 nan,
 'E11',
 'B00',
 'K29',
 'Z35',
 nan,
 'K29',
 'E56',
 'L08',
 'K30',
 'M79',
 'K29',
 'Z00',
 'A75',
 nan,
 'O80',
 'E11',
 'O16',
 'I11',
 nan,
 'R10',
 'Z09',
 'L23',
 'L23',
 nan,
 'J06',
 'J06',
 'Z34',
 nan,
 'O21',
 'I10',
 'G44',
 'K29',
 'M79',
 'I10',
 'D64',
 'Z82',
 'I10',
 'K04',
 'M10',
 nan,
 'K29',
 nan,
 'I11',
 'J06',
 'J30',
 nan,
 nan,
 'I00',
 'J06',
 'I10',
 nan,
 nan,
 'K00',
 'O00',
 'J00',
 'K35',
 'L24',
 'H66',
 nan,
 nan,
 nan,
 'L20',
 nan,
 nan,
 'J02',
 'H26',
 'I50',
 'I10',
 'H60',
 'G43',
 nan,
 nan,
 'R50',
 nan,
 'J45',
 'N39',
 nan,
 nan,
 'J00',
 'J06',
 'J45',
 'M79',
 nan,
 'E11',
 'J00',
 'Z30',
 'K29',
 'K04',
 'I21',
 'E11',
 'J06',
 nan,
 nan,
 'M79',
 'L03',
 'K29',
 'I84',
 'K02',
 'Z30',
 nan,
 nan,
 'H90',
 nan,
 nan,
 'J06',
 'K04',
 'T14',
 nan,
 nan,
 'K29',
 nan,
 'E10',
 'N39',
 nan,
 'I10',
 nan,
 'K30',
 'Z36',
 'J11',
 nan,
 nan,
 'E11',
 nan,
 'K30',
 'J02',
 'G44',
 'Z92',
 nan,
 nan,
 nan,
 'B01',
 'M17',
 nan,
 nan,
 'Z09',
 nan,
 'I20',
 'M79',
 'L30',
 'R50',
 'E14',
 nan,
 nan,
 'I84',
 nan,
 nan,
 nan,
 'A16',
 nan,
 'E11',
 'I10',
 'J06',
 'J06',
 nan,
 'J02',
 'L23',
 'G43',
 'R51',
 'J06',
 'T81',
 nan,
 nan,
 'J01',
 nan,
 'A16',
 'I10',
 nan,
 'J02',
 'K30',
 'J06',
 nan,
 'J00',
 nan,
 'Z30',
 'K29',
 nan,
 'K30',
 nan,
 nan,
 nan,
 'Z36',
 nan,
 'M79',
 nan,
 nan,
 'Z12',
 nan,
 'M15',
 'A09',
 nan,
 'J22',
 'H60',
 'H60',
 'Z34',
 'J00',
 'K01',
 'H57',
 nan,
 'K04',
 'K04',
 'I10',
 'J20',
 nan,
 nan,
 'L98',
 'J06',
 'I63',
 nan,
 'J06',
 'K04',
 nan,
 'B26',
 'I20',
 'G43',
 nan,
 'K04',
 nan,
 nan,
 'J06',
 'E11',
 'L30',
 'L25',
 nan,
 'I10',
 'H66',
 nan,
 nan,
 'J06',
 'M79',
 'V18',
 'Z01',
 'H26',
 nan,
 'R50',
 'J02',
 nan,
 'R50',
 nan,
 'Z00',
 'R51',
 'M25',
 'J06',
 'Z97',
 'E10',
 'E11',
 'J00',
 'A09',
 nan,
 'T14',
 nan,
 'R50',
 nan,
 'R50',
 nan,
 nan,
 'K04',
 'Z30',
 'R05',
 'R10',
 'O80',
 nan,
 'M10',
 'J00',
 nan,
 nan,
 nan,
 'K62',
 nan,
 nan,
 'J00',
 nan,
 'B86',
 nan,
 'K30',
 'J00',
 'J12',
 'J02',
 nan,
 'J06',
 'I10',
 'E11',
 nan,
 'J06',
 'Z36',
 nan,
 'E11',
 'J06',
 'K04',
 nan,
 'I10',
 'R50',
 'A77',
 'M13',
 'B87',
 nan,
 nan,
 'E11',
 'M54',
 'J06',
 'J06',
 'E11',
 nan,
 nan,
 nan,
 'J03',
 nan,
 'Z36',
 'K30',
 'K29',
 'I10',
 'G51',
 'A15',
 'M79',
 'J01',
 'M54',
 nan,
 nan,
 'J06',
 'R51',
 'K29',
 nan,
 'Z00',
 'F20',
 'E11',
 'J06',
 nan,
 'E05',
 'J40',
 'Z30',
 nan,
 'K02',
 'J81',
 'K30',
 'H81',
 nan,
 nan,
 nan,
 'I10',
 'M79',
 'G44',
 'I10',
 nan,
 nan,
 'J00',
 nan,
 nan,
 nan,
 nan,
 nan,
 'M54',
 'J11',
 'K29',
 nan,
 'K30',
 'M19',
 'I11',
 nan,
 'A01',
 nan,
 'K30',
 nan,
 'R51',
 nan,
 'B86',
 nan,
 nan,
 'K04',
 nan,
 'J00',
 'J00',
 'K04',
 nan,
 'M79',
 'I10',
 'M79',
 'B35',
 'Z00',
 'A09',
 'K29',
 'Z09',
 'O02',
 'E11',
 'K30',
 'L20',
 'J00',
 nan,
 nan,
 'K29',
 'J00',
 'J03',
 'H10',
 nan,
 'K02',
 'A09',
 'J00',
 nan,
 'R07',
 nan,
 'K29',
 'J02',
 'M79',
 'J00',
 nan,
 'J02',
 'K29',
 nan,
 'K29',
 nan,
 'D21',
 'F32',
 'J00',
 'G43',
 'J00',
 'J00',
 nan,
 nan,
 'Z09',
 'K30',
 'Z34',
 'K30',
 'K04',
 'K05',
 'K04',
 nan,
 'K04',
 'L30',
 nan,
 nan,
 'K29',
 'Z35',
 nan,
 'E79',
 'L02',
 'K02',
 'K29',
 'Z35',
 nan,
 'M79',
 'R50',
 'E11',
 'O26',
 'F51',
 'H10',
 nan,
 'I10',
 'J06',
 'E11',
 'Z00',
 nan,
 'K30',
 'J45',
 'J06',
 nan,
 nan,
 'A09',
 'M79',
 'J06',
 'F20',
 'S50',
 'A09',
 'J06',
 'J06',
 'J11',
 'Z00',
 'K29',
 'H81',
 nan,
 nan,
 nan,
 'J06',
 nan,
 nan,
 nan,
 'I10',
 nan,
 'M54',
 'J47',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'K05',
 'M06',
 'A78',
 'Z00',
 nan,
 'Z34',
 'R10',
 'R05',
 'M06',
 'F20',
 'I15',
 'J03',
 'I10',
 'A09',
 'J06',
 'Z30',
 'L20',
 'R05',
 'H10',
 nan,
 'K04',
 'K04',
 'J00',
 'I50',
 nan,
 'I10',
 'D50',
 'R05',
 'M54',
 'R53',
 'K05',
 nan,
 'F20',
 nan,
 'M54',
 'A15',
 'J45',
 nan,
 nan,
 nan,
 'Z35',
 nan,
 'Z71',
 nan,
 'Z34',
 nan,
 'K30',
 'R50',
 'K29',
 'K30',
 nan,
 'J02',
 nan,
 'J06',
 nan,
 'B01',
 'Z35',
 ...]

In [14]:
#menghitung missing value
mydata_test.isnull().sum()

Nomor peserta                                            0
Nomor keluarga                                           0
Bobot                                                    0
ID Kunjungan FKTP                                        0
Tanggal datang kunjungan FKTP                            0
Tanggal pulang kunjungan FKTP                            0
Provinsi FKTP                                            0
Kabupaten/Kota FKTP                                      0
Kepemilikan FKTP                                         0
Jenis FKTP                                               0
Tipe FKTP                                                0
Tingkat Pelayanan FKTP                                   0
Jenis Poli FKTP                                          0
Segmen Peserta saat akses layanan FKTP                   0
Kode dan nama diagnosis ICD 10 (3 digit)                 0
Kode diagnosis ICD 10 (3 digit)                     345912
Kode diagnosis (beragam 3-5 digit)                       0
Nama diagnosis berasal dari kode diagnosis FKP15         0
Provinsi faskes tujuan rujukan                           0
Kabupaten/Kota faskes tujuan rujukan                     0
Kepemilikan faskes tujuan rujukan                        0
Jenis faskes tujuan rujukan                              0
Tipe faskes tujuan rujukan                               0
Poli faskes tujuan rujukan                               0
Jenis Kunjungan FKTP                                     0
dtype: int64

In [15]:
mydata_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014225 entries, 0 to 1014224
Data columns (total 25 columns):
 #   Column                                            Non-Null Count    Dtype
---  ------                                            --------------    -----
 0   Nomor peserta                                     1014225 non-null  float64
 1   Nomor keluarga                                    1014225 non-null  int64
 2   Bobot                                             1014225 non-null  float64
 3   ID Kunjungan FKTP                                 1014225 non-null  object
 4   Tanggal datang kunjungan FKTP                     1014225 non-null  object
 5   Tanggal pulang kunjungan FKTP                     1014225 non-null  object
 6   Provinsi FKTP                                     1014225 non-null  int64
 7   Kabupaten/Kota FKTP                               1014225 non-null  int64
 8   Kepemilikan FKTP                                  1014225 non-null  int64
 9   Jenis FKTP                                        1014225 non-null  int64
 10  Tipe FKTP                                         1014225 non-null  int64
 11  Tingkat Pelayanan FKTP                            1014225 non-null  int64
 12  Jenis Poli FKTP                                   1014225 non-null  int64
 13  Segmen Peserta saat akses layanan FKTP            1014225 non-null  int64
 14  Kode dan nama diagnosis ICD 10 (3 digit)          1014225 non-null  int64
 15  Kode diagnosis ICD 10 (3 digit)                   668313 non-null   object
 16  Kode diagnosis (beragam 3-5 digit)                1014225 non-null  object
 17  Nama diagnosis berasal dari kode diagnosis FKP15  1014225 non-null  object
 18  Provinsi faskes tujuan rujukan                    1014225 non-null  int64
 19  Kabupaten/Kota faskes tujuan rujukan              1014225 non-null  int64
 20  Kepemilikan faskes tujuan rujukan                 1014225 non-null  int64
 21  Jenis faskes tujuan rujukan                       1014225 non-null  int64
 22  Tipe faskes tujuan rujukan                        1014225 non-null  int64
 23  Poli faskes tujuan rujukan                        1014225 non-null  int64
 24  Jenis Kunjungan FKTP                              1014225 non-null  int64
dtypes: float64(2), int64(17), object(6)
memory usage: 193.4+ MB

In [16]:
mydata_test.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1014220    False
1014221    False
1014222    False
1014223    False
1014224    False
Length: 1014225, dtype: bool

In [17]:
#drop

#train data set
mydata_train = mydata_train.drop(columns = ['Nomor keluarga','ID Kunjungan FKTP', 'Kode diagnosis ICD 10 (3 digit)',
                                        'Tanggal datang kunjungan FKTP', 'Tanggal pulang kunjungan FKTP', 
                                        'Nama diagnosis berasal dari kode diagnosis FKP15',
                                        'Kode diagnosis (beragam 3-5 digit)'], inplace = False, axis = 1)

#test data set
mydata_test = mydata_test.drop(columns = ['Nomor keluarga','ID Kunjungan FKTP', 'Kode diagnosis ICD 10 (3 digit)',
                                        'Tanggal datang kunjungan FKTP', 'Tanggal pulang kunjungan FKTP', 
                                        'Nama diagnosis berasal dari kode diagnosis FKP15',
                                        'Kode diagnosis (beragam 3-5 digit)'], inplace = False, axis = 1)

In [18]:
#cek jenis data
mydata_train.isnull().sum()

Nomor peserta                               0
Bobot                                       0
Provinsi FKTP                               0
Kabupaten/Kota FKTP                         0
Kepemilikan FKTP                            0
Jenis FKTP                                  0
Tipe FKTP                                   0
Tingkat Pelayanan FKTP                      0
Jenis Poli FKTP                             0
Segmen Peserta saat akses layanan FKTP      0
Kode dan nama diagnosis ICD 10 (3 digit)    0
Provinsi faskes tujuan rujukan              0
Kabupaten/Kota faskes tujuan rujukan        0
Kepemilikan faskes tujuan rujukan           0
Jenis faskes tujuan rujukan                 0
Tipe faskes tujuan rujukan                  0
Poli faskes tujuan rujukan                  0
Jenis Kunjungan FKTP                        0
Kelas Status Pulang Peserta                 0
dtype: int64

In [19]:
#menghitung missing value
mydata_test.isnull().sum()

Nomor peserta                               0
Bobot                                       0
Provinsi FKTP                               0
Kabupaten/Kota FKTP                         0
Kepemilikan FKTP                            0
Jenis FKTP                                  0
Tipe FKTP                                   0
Tingkat Pelayanan FKTP                      0
Jenis Poli FKTP                             0
Segmen Peserta saat akses layanan FKTP      0
Kode dan nama diagnosis ICD 10 (3 digit)    0
Provinsi faskes tujuan rujukan              0
Kabupaten/Kota faskes tujuan rujukan        0
Kepemilikan faskes tujuan rujukan           0
Jenis faskes tujuan rujukan                 0
Tipe faskes tujuan rujukan                  0
Poli faskes tujuan rujukan                  0
Jenis Kunjungan FKTP                        0
dtype: int64

In [20]:
#hitung data sehat/enggak
mydata_train['Kelas Status Pulang Peserta'].value_counts()

Belum_Sehat    2634511
Sehat          1422387
Name: Kelas Status Pulang Peserta, dtype: int64

In [21]:
#check missing value train dataset
mydata_train.isna()

,Nomor peserta,Bobot,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,Tipe FKTP,Tingkat Pelayanan FKTP,Jenis Poli FKTP,Segmen Peserta saat akses layanan FKTP,Kode dan nama diagnosis ICD 10 (3 digit),Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP,Kelas Status Pulang Peserta
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4056893,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4056894,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4056895,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4056896,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4056897,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [22]:
mydata_train['Nomor peserta'] = mydata_train['Nomor peserta'].astype('object')
mydata_train['Provinsi FKTP'] = mydata_train['Provinsi FKTP'].astype('object')
mydata_train['Kabupaten/Kota FKTP'] = mydata_train['Kabupaten/Kota FKTP'].astype('object')
mydata_train['Kepemilikan FKTP'] = mydata_train['Kepemilikan FKTP'].astype('object')
mydata_train['Jenis FKTP'] = mydata_train['Jenis FKTP'].astype('object')
mydata_train['Tipe FKTP'] = mydata_train['Tipe FKTP'].astype('object')
mydata_train['Tingkat Pelayanan FKTP'] = mydata_train['Tingkat Pelayanan FKTP'].astype('object')
mydata_train['Jenis Poli FKTP'] = mydata_train['Jenis Poli FKTP'].astype('object')
mydata_train['Segmen Peserta saat akses layanan FKTP'] = mydata_train['Segmen Peserta saat akses layanan FKTP'].astype('object')
mydata_train['Kode dan nama diagnosis ICD 10 (3 digit)'] = mydata_train['Kode dan nama diagnosis ICD 10 (3 digit)'].astype('category')
mydata_train['Provinsi faskes tujuan rujukan'] = mydata_train['Provinsi faskes tujuan rujukan'].astype('object')
mydata_train['Kabupaten/Kota faskes tujuan rujukan'] = mydata_train['Kabupaten/Kota faskes tujuan rujukan'].astype('object')
mydata_train['Kepemilikan faskes tujuan rujukan'] = mydata_train['Kepemilikan faskes tujuan rujukan'].astype('object')
mydata_train['Jenis faskes tujuan rujukan'] = mydata_train['Jenis faskes tujuan rujukan'].astype('object')
mydata_train['Tipe faskes tujuan rujukan'] = mydata_train['Tipe faskes tujuan rujukan'].astype('object')
mydata_train['Poli faskes tujuan rujukan'] = mydata_train['Poli faskes tujuan rujukan'].astype('object')
mydata_train['Jenis Kunjungan FKTP'] = mydata_train['Jenis Kunjungan FKTP'].astype('object')

mydata_test['Nomor peserta'] = mydata_test['Nomor peserta'].astype('object')
mydata_test['Provinsi FKTP'] = mydata_test['Provinsi FKTP'].astype('object')
mydata_test['Kabupaten/Kota FKTP'] = mydata_test['Kabupaten/Kota FKTP'].astype('object')
mydata_test['Kepemilikan FKTP'] = mydata_test['Kepemilikan FKTP'].astype('object')
mydata_test['Jenis FKTP'] = mydata_test['Jenis FKTP'].astype('object')
mydata_test['Tipe FKTP'] = mydata_test['Tipe FKTP'].astype('object')
mydata_test['Tingkat Pelayanan FKTP'] = mydata_test['Tingkat Pelayanan FKTP'].astype('object')
mydata_test['Jenis Poli FKTP'] = mydata_test['Jenis Poli FKTP'].astype('object')
mydata_test['Segmen Peserta saat akses layanan FKTP'] = mydata_test['Segmen Peserta saat akses layanan FKTP'].astype('object')
mydata_test['Kode dan nama diagnosis ICD 10 (3 digit)'] = mydata_test['Kode dan nama diagnosis ICD 10 (3 digit)'].astype('category')
mydata_test['Provinsi faskes tujuan rujukan'] = mydata_test['Provinsi faskes tujuan rujukan'].astype('object')
mydata_test['Kabupaten/Kota faskes tujuan rujukan'] = mydata_test['Kabupaten/Kota faskes tujuan rujukan'].astype('object')
mydata_test['Kepemilikan faskes tujuan rujukan'] = mydata_test['Kepemilikan faskes tujuan rujukan'].astype('object')
mydata_test['Jenis faskes tujuan rujukan'] = mydata_test['Jenis faskes tujuan rujukan'].astype('object')
mydata_test['Tipe faskes tujuan rujukan'] = mydata_test['Tipe faskes tujuan rujukan'].astype('object')
mydata_test['Poli faskes tujuan rujukan'] = mydata_test['Poli faskes tujuan rujukan'].astype('object')
mydata_test['Jenis Kunjungan FKTP'] = mydata_test['Jenis Kunjungan FKTP'].astype('object')

In [23]:
mydata_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4056898 entries, 0 to 4056897
Data columns (total 19 columns):
 #   Column                                    Dtype
---  ------                                    -----
 0   Nomor peserta                             object
 1   Bobot                                     float64
 2   Provinsi FKTP                             object
 3   Kabupaten/Kota FKTP                       object
 4   Kepemilikan FKTP                          object
 5   Jenis FKTP                                object
 6   Tipe FKTP                                 object
 7   Tingkat Pelayanan FKTP                    object
 8   Jenis Poli FKTP                           object
 9   Segmen Peserta saat akses layanan FKTP    object
 10  Kode dan nama diagnosis ICD 10 (3 digit)  category
 11  Provinsi faskes tujuan rujukan            object
 12  Kabupaten/Kota faskes tujuan rujukan      object
 13  Kepemilikan faskes tujuan rujukan         object
 14  Jenis faskes tujuan rujukan               object
 15  Tipe faskes tujuan rujukan                object
 16  Poli faskes tujuan rujukan                object
 17  Jenis Kunjungan FKTP                      object
 18  Kelas Status Pulang Peserta               object
dtypes: category(1), float64(1), object(17)
memory usage: 564.9+ MB

In [24]:
mydata_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014225 entries, 0 to 1014224
Data columns (total 18 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   Nomor peserta                             1014225 non-null  object
 1   Bobot                                     1014225 non-null  float64
 2   Provinsi FKTP                             1014225 non-null  object
 3   Kabupaten/Kota FKTP                       1014225 non-null  object
 4   Kepemilikan FKTP                          1014225 non-null  object
 5   Jenis FKTP                                1014225 non-null  object
 6   Tipe FKTP                                 1014225 non-null  object
 7   Tingkat Pelayanan FKTP                    1014225 non-null  object
 8   Jenis Poli FKTP                           1014225 non-null  object
 9   Segmen Peserta saat akses layanan FKTP    1014225 non-null  object
 10  Kode dan nama diagnosis ICD 10 (3 digit)  1014225 non-null  category
 11  Provinsi faskes tujuan rujukan            1014225 non-null  object
 12  Kabupaten/Kota faskes tujuan rujukan      1014225 non-null  object
 13  Kepemilikan faskes tujuan rujukan         1014225 non-null  object
 14  Jenis faskes tujuan rujukan               1014225 non-null  object
 15  Tipe faskes tujuan rujukan                1014225 non-null  object
 16  Poli faskes tujuan rujukan                1014225 non-null  object
 17  Jenis Kunjungan FKTP                      1014225 non-null  object
dtypes: category(1), float64(1), object(16)
memory usage: 133.6+ MB

In [25]:
columns = ['Bobot']
scaler = StandardScaler()
mydata_train_scale = scaler.fit_transform(mydata_train[columns])
mydata_test_scale = scaler.fit_transform(mydata_test[columns])

In [26]:
mydata_train_scale

array([[-0.45368351],
       [-0.54612411],
       [-0.55447025],
       ...,
       [-0.52746622],
       [-0.41931334],
       [-0.09171733]])

In [27]:
mydata_test_scale

array([[ 0.7216915 ],
       [-0.31123087],
       [-0.53273159],
       ...,
       [ 0.96674427],
       [-0.40281057],
       [ 0.68299894]])

In [28]:
#convert bobot column dengan data yang telah di standardisasi
mydata_train["Bobot"] = mydata_train_scale
mydata_test["Bobot"] = mydata_test_scale

In [29]:
mydata_train

,Nomor peserta,Bobot,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,Tipe FKTP,Tingkat Pelayanan FKTP,Jenis Poli FKTP,Segmen Peserta saat akses layanan FKTP,Kode dan nama diagnosis ICD 10 (3 digit),Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP,Kelas Status Pulang Peserta
0,157978748.0,-0.453684,61,6108,3,1,4,1,12.0,2,9999,98,9998,98,98,98,98,2,Sehat
1,95085112.0,-0.546124,51,5171,9,3,2,1,1.0,4,773,98,9998,98,98,98,98,1,Belum_Sehat
2,224470578.0,-0.554470,35,3516,9,2,1,1,3.0,4,1757,98,9998,98,98,98,98,1,Belum_Sehat
3,63871289.0,1.373410,34,3402,3,1,4,1,1.0,5,621,98,9998,98,98,98,98,1,Belum_Sehat
4,29915626.0,-0.554477,35,3509,3,1,4,1,1.0,1,622,98,9998,98,98,98,98,1,Belum_Sehat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4056893,212666736.0,-0.484528,35,3505,9,3,2,1,12.0,4,9999,98,9998,98,98,98,98,2,Sehat
4056894,30859241.0,-0.539442,35,3514,9,2,1,1,1.0,5,561,35,3514,9,2,14,99,1,Belum_Sehat
4056895,8859416.0,-0.527466,11,1171,4,2,1,1,13.0,5,9999,98,9998,98,98,98,98,2,Sehat
4056896,399491834.0,-0.419313,74,7402,3,1,3,1,1.0,2,774,98,9998,98,98,98,98,1,Belum_Sehat
4056897,99146724.0,-0.091717,73,7317,3,1,4,1,13.0,2,9999,98,9998,98,98,98,98,2,Sehat

In [30]:
mydata_test

,Nomor peserta,Bobot,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,Tipe FKTP,Tingkat Pelayanan FKTP,Jenis Poli FKTP,Segmen Peserta saat akses layanan FKTP,Kode dan nama diagnosis ICD 10 (3 digit),Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP
0,187883292.0,0.721692,31,3172,9,2,1,1,13,5,9999,98,9998,98,98,98,98,2
1,123307139.0,-0.311231,17,1705,3,1,3,1,12,2,9999,98,9998,98,98,98,98,2
2,21416273.0,-0.532732,64,6402,3,1,4,1,13,2,9999,98,9998,98,98,98,98,2
3,97630052.0,0.358879,18,1872,9,2,5,1,13,5,9999,98,9998,98,98,98,98,2
4,124531163.0,0.435142,18,1809,9,2,5,1,13,2,9999,98,9998,98,98,98,98,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014220,51801010.0,-0.523759,36,3601,9,2,1,1,1,4,1818,36,3602,3,1,27,99,1
1014221,339397889.0,-0.505078,33,3373,9,2,1,1,1,4,1818,98,9998,98,98,98,98,1
1014222,76213152.0,0.966744,32,3276,3,1,3,1,1,5,1818,32,3276,9,1,33,99,1
1014223,101797983.0,-0.402811,16,1606,3,1,3,1,1,4,1818,16,1606,3,1,27,99,1
1014224,20239553.0,0.682999,19,1904,3,1,3,1,1,2,1818,19,1971,3,1,28,99,1

In [31]:
#label encoder. mengubah status sehat menjadi 1, status tidak sehat menjadi 0.
encoder = LabelBinarizer()
encoder.fit(mydata_train["Kelas Status Pulang Peserta"])

mydata_train["Kelas Status Pulang Peserta"] = encoder.transform(mydata_train["Kelas Status Pulang Peserta"])

In [32]:
mydata_train

,Nomor peserta,Bobot,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,Tipe FKTP,Tingkat Pelayanan FKTP,Jenis Poli FKTP,Segmen Peserta saat akses layanan FKTP,Kode dan nama diagnosis ICD 10 (3 digit),Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP,Kelas Status Pulang Peserta
0,157978748.0,-0.453684,61,6108,3,1,4,1,12.0,2,9999,98,9998,98,98,98,98,2,1
1,95085112.0,-0.546124,51,5171,9,3,2,1,1.0,4,773,98,9998,98,98,98,98,1,0
2,224470578.0,-0.554470,35,3516,9,2,1,1,3.0,4,1757,98,9998,98,98,98,98,1,0
3,63871289.0,1.373410,34,3402,3,1,4,1,1.0,5,621,98,9998,98,98,98,98,1,0
4,29915626.0,-0.554477,35,3509,3,1,4,1,1.0,1,622,98,9998,98,98,98,98,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4056893,212666736.0,-0.484528,35,3505,9,3,2,1,12.0,4,9999,98,9998,98,98,98,98,2,1
4056894,30859241.0,-0.539442,35,3514,9,2,1,1,1.0,5,561,35,3514,9,2,14,99,1,0
4056895,8859416.0,-0.527466,11,1171,4,2,1,1,13.0,5,9999,98,9998,98,98,98,98,2,1
4056896,399491834.0,-0.419313,74,7402,3,1,3,1,1.0,2,774,98,9998,98,98,98,98,1,0
4056897,99146724.0,-0.091717,73,7317,3,1,4,1,13.0,2,9999,98,9998,98,98,98,98,2,1

In [33]:
#split data train set
x = mydata_train.iloc[:,0:18].values
y = mydata_train.iloc[:,18:22].values

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state = 0)

In [35]:
import warnings

warnings.filterwarnings('ignore')
from sklearn.ensemble import RandomForestClassifier
rfc_100 = RandomForestClassifier(n_estimators=100, random_state=0)



# fit the model to the training set

rfc_100.fit(x_train, y_train)



# Predict on the test set results

y_pred_100 = rfc_100.predict(x_val)



# Check accuracy score 

print('Model accuracy score with 100 decision-trees : {0:0.4f}'. format(accuracy_score(y_val, y_pred_100)))

Model accuracy score with 100 decision-trees : 0.9978

In [36]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_val, y_pred_100)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[526614    555]
 [  1237 282974]]

In [37]:
from sklearn.metrics import classification_report

print(classification_report(y_val, y_pred_100))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    527169
           1       1.00      1.00      1.00    284211

    accuracy                           1.00    811380
   macro avg       1.00      1.00      1.00    811380
weighted avg       1.00      1.00      1.00    811380

In [38]:
y_pred_100.tolist()

[0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 ...]

In [39]:
prediction=rfc_100.predict(np.asarray(mydata_test).astype(np.int32))

In [40]:
prediction.tolist()

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 ...]

In [41]:
mydata_test['target']=prediction

In [42]:
mydata_test

,Nomor peserta,Bobot,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,Tipe FKTP,Tingkat Pelayanan FKTP,Jenis Poli FKTP,Segmen Peserta saat akses layanan FKTP,Kode dan nama diagnosis ICD 10 (3 digit),Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP,target
0,187883292.0,0.721692,31,3172,9,2,1,1,13,5,9999,98,9998,98,98,98,98,2,1
1,123307139.0,-0.311231,17,1705,3,1,3,1,12,2,9999,98,9998,98,98,98,98,2,1
2,21416273.0,-0.532732,64,6402,3,1,4,1,13,2,9999,98,9998,98,98,98,98,2,1
3,97630052.0,0.358879,18,1872,9,2,5,1,13,5,9999,98,9998,98,98,98,98,2,1
4,124531163.0,0.435142,18,1809,9,2,5,1,13,2,9999,98,9998,98,98,98,98,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014220,51801010.0,-0.523759,36,3601,9,2,1,1,1,4,1818,36,3602,3,1,27,99,1,0
1014221,339397889.0,-0.505078,33,3373,9,2,1,1,1,4,1818,98,9998,98,98,98,98,1,0
1014222,76213152.0,0.966744,32,3276,3,1,3,1,1,5,1818,32,3276,9,1,33,99,1,0
1014223,101797983.0,-0.402811,16,1606,3,1,3,1,1,4,1818,16,1606,3,1,27,99,1,0
1014224,20239553.0,0.682999,19,1904,3,1,3,1,1,2,1818,19,1971,3,1,28,99,1,0

In [43]:
mydata_test['target'].value_counts()

0    659210
1    355015
Name: target, dtype: int64

In [44]:
#cek overfitting atau kagak, kalau hasil training score dan test score nya beda jauh, berarti overfitiing
print('training score:{:.4f}'.format(rfc_100.score(x_train,y_train)))
print('test score:{:.4f}'.format(rfc_100.score(x_val,y_val)))

training score:0.9987
test score:0.9978

In [46]:
#drop

#test data set
mydata_test = mydata_test.drop(columns = ['Bobot','Provinsi FKTP', 'Kabupaten/Kota FKTP', 'Kepemilikan FKTP', 'Jenis FKTP', 
                                          'Tipe FKTP','Tingkat Pelayanan FKTP', "Jenis Poli FKTP", 'Segmen Peserta saat akses layanan FKTP',
                                          'Kode dan nama diagnosis ICD 10 (3 digit)','Provinsi faskes tujuan rujukan',
                                          'Kabupaten/Kota faskes tujuan rujukan', 'Kepemilikan faskes tujuan rujukan',
                                          'Jenis faskes tujuan rujukan', 'Tipe faskes tujuan rujukan',
                                          'Poli faskes tujuan rujukan', 'Jenis Kunjungan FKTP'], inplace = False, axis = 1)

In [47]:
mydata_test

        Nomor peserta  target
0         187883292.0       1
1         123307139.0       1
2          21416273.0       1
3          97630052.0       1
4         124531163.0       1
...               ...     ...
1014220    51801010.0       0
1014221   339397889.0       0
1014222    76213152.0       0
1014223   101797983.0       0
1014224    20239553.0       0

[1014225 rows x 2 columns]

In [49]:
mydata_test.to_csv("C:/E_Drive/data zinedine/masa kuliah/matkul smt 5/Project BDC/submission.csv")